### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by antboy** [matsim-org/GTFS2MATSim#13]
Hi,
it would be nice if your code (RunGTFS2MATSim.java, and any others) used logging instead of printing to console (System.out.println), so that all output could be logged to a file.

If you used the SLF4J facade library, then we could decide on which logging system to bind to it, but LOG4J would be a reasonable 2nd best (as that's what Matsim uses).

Thanks for your project.

**Comment by jfbischoff** [comment]
I've recently refactored the println statements. Most of them were not too useful, anyway.
