### ISSUE TITLE
merging two GTFS feeds into one

### ISSUE THREAD

**Issue by vsgo222** [matsim-org/GTFS2MATSim#25]
Hello all,
I am working with San Francisco city-data. SF area has two primary GTFS feeds. 
Is there a way I can combine two GTFS feeds before calling the GTFS2MATSim class file or passing the individually GTFS feed is an appropriate step?

**Comment by ikaddoura** [comment]
What I typically do in such cases: Generate a transit schedule, transit vehicles and a network for each GTFS file and then merge the schedules, vehicles and networks in a second step.

See here: https://github.com/matsim-scenarios/matsim-metropole-ruhr/blob/master/src/main/java/org/matsim/prepare/CreateSupply.java

or here: https://github.com/matsim-scenarios/matsim-los-angeles/blob/v1.1/src/main/java/org/matsim/prepare/MergeTransitFiles.java

**Comment by vsgo222** [comment]
Thank you @ikaddoura. This is useful.

**Comment by vsgo222** [comment]
@ikaddoura: 
I created transitSchedule and transitVehicle files using GTFS2MATSim plugin. I later used, MergeTransitFiles.java script to merge these two files into one as recommended. I get an error when running the MergeTransitFiles.java script but the script failed in merging the second transitVehicle because of two reasons
1. the log says, `id="defaultTransitVehicleType"` is already present. So, I inserted an if condition before the for loop:
```
if (baseTransitVehicles.getVehicleTypes().isEmpty()) {
            for (VehicleType vehicleType : transitVehicles.getVehicleTypes().values()) {
                VehicleType vehicleType2 = baseTransitVehicles.getFactory().createVehicleType(vehicleType.getId());
                vehicleType2.setNetworkMode(vehicleType.getNetworkMode());
                vehicleType2.setPcuEquivalents(vehicleType.getPcuEquivalents());
                vehicleType2.setDescription(vehicleType.getDescription());
                vehicleType2.getCapacity().setSeats(vehicleType.getCapacity().getSeats());
                baseTransitVehicles.addVehicleType(vehicleType2);
            }
        }
```
2. Also somehow, vehicleID in both GTFS feeds got allocated the same ids. I think it has something to do with the way GTFS2MATSim creates transitVehicle files. e.g. everything starts from "tr_*" because of `Vehicle veh = vb.createVehicle(Id.create("tr_" + Long.toString(vehId++), Vehicle.class), vehicleType);` which produces conflict. I manually changed the suffix in the files as I wasn't able to change in the code. 

I know my solution is not user-friendly and would like to know if there is a suitable way to handle it?

**Comment by ikaddoura** [comment]
Thanks for reaching out to us. You need to adjust the script which generates the transit vehicle type and vehicles. You need to make sure that some unique identifier is used in the ID of both the vehicle type and the vehicle itself. Have a look at this code snippet: https://github.com/matsim-scenarios/matsim-los-angeles/blob/5f589ea627594c9f2a63aa9861f2f95f2a37e446/src/main/java/org/matsim/prepare/CreateTransitScheduleAndVehiclesFromGTFS.java#L143

**Comment by rakow** [comment]
There is now a prefix option to create unique ids. The CLI tool also supports multiple gtfs feeds:
https://github.com/matsim-org/matsim-libs/blob/master/contribs/application/src/main/java/org/matsim/application/prepare/pt/CreateTransitScheduleFromGtfs.java
