### ISSUE TITLE
Could you add a license?

### ISSUE THREAD

**Issue by marecabo** [matsim-org/GTFS2MATSim#33]
Dear MATSim Community, 

this component has currently no license file. Could we add one, so this code is usable? I would suggest to use the same license as the matsim-libs project (https://github.com/matsim-org/matsim-libs/blob/master/matsim/COPYING) and the pt2matsim project (https://github.com/matsim-org/pt2matsim/blob/master/LICENSE).

**Comment by marecabo** [comment]
Some Java files even reference the license files from the main matsim-libs repo, so I guess, they just have been forgotten?
https://github.com/matsim-org/GTFS2MATSim/blob/0bd5850fd694ea9a4e9fecc47443d4992ce7270f/src/main/java/org/matsim/contrib/gtfs/CreateVehicleCirculation.java#L1-L18

**Comment by jfbischoff** [comment]
Seems like a classic problem if a toy-software project becomes productive code 😆 
I will add the GPL license file, since in fact many files reference to it..... and all of the developers of this project are also part of matsim-libs.
